export const SITE_NAME = 'aloshy.ai | Starter'
export const SITE_SHORT_NAME = 'Starter'
export const SITE_DESCRIPTION = 'Starter template for Next.js with Supabase'
export const SITE_DOMAIN = 'https://starter.aloshy.ai'
export const PROTECTED_ROUTE = '/protected'
